name: Print Secret Variable

on:
  push:
    branches:
      - main 

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: secrets  

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2

      - name: Build Docker image from code
        run: |

      - name: Log in to DockerHub (если вы используете Docker Hub)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub (если используете Docker Hub)
        run: |
          docker tag link-shortner-site:latest kenueyy/link-shortner-site:latest
          docker push kenueyy/link-shortner-site:latest

      - name: SSH to server and deploy the Docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Обновление контейнера на сервере
            docker pull your-dockerhub-username/your-app:latest
            docker stop your-app-container || true
            docker rm your-app-container || true
            docker run -d --name your-app-container -p 80:80 your-dockerhub-username/your-app:latest
